import type { Metadata } from "next";
import { Space_Grotesk, Instrument_Sans } from "next/font/google";
import { themeClass } from "@/styles/theme.css";
import type { Viewport } from "next";

import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VaultPay",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "2900",
  initialScale: 1,

  height: "900",
  colorScheme: "only light",
  viewportFit: "cover",
  maximumScale: 4,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${instrumentSans.variable} antialiased ${themeClass}`}
      >
        {children}
      </body>
    </html>
  );
}
